const MOVES = {

  // ── 노말 ──────────────────────────────────
  "전광석화": {
    name: "전광석화",
    type: "노말",
    category: "물리",
    power: 30,
    accuracy: null,
    pp: 30,
    priority: 1,
    rankChange: null,
    effect: null,
    alwaysHit: true,
    description: "눈에 보이지 않는 굉장한 속도로 상대에게 돌진한다. 반드시 명중한다.",
  },

  "방어": {
    name: "방어",
    type: "노말",
    category: "물리",
    power: null,
    accuracy: null,
    pp: 10,
    priority: 1,
    rankChange: null,
    effect: "방어의 효과는 사용한 턴을 포함해 최대 2턴 지속(자신 기준)",
    alwaysHit: null,
    description: "상대의 공격을 전혀 받지 않는다. 연속으로 쓰면 실패하기 쉽다.",
  },

  "눈물그렁그렁": {
    name: "눈물그렁그렁",
    type: "노말",
    category: "물리",
    power: null,
    accuracy: null,
    pp: 20,
    priority: 1,
    rankChange: { target: "foe", stat: "atk", stage: -1 },
    effect: null,
    alwaysHit: null,
    description: "눈물을 그렁그렁거려 상대의 전의를 상실하게 한다. 상대의 공격이 -1 하락한다.",
  },

  "칼춤": {
    name: "칼춤",
    type: "노말",
    category: "변화",
    power: null,
    accuracy: null,
    pp: 20,
    priority: 0,
    rankChange: { target: "self", stat: "atk", stage: 3 },
    effect: null,
    alwaysHit: false,
    description: "싸움의 춤을 격렬하게 춰서 기세를 높인다. 자신의 공격이 +3 상승한다.",
  },

  "몸통박치기": {
    name: "몸통박치기",
    type: "노말",
    category: "물리",
    power: 30,
    accuracy: 100,
    pp: 35,
    priority: 1,
    rankChange: null,
    effect: null,
    alwaysHit: null,
    description: "상대를 향해서 몸 전체를 부딪쳐가며 공격한다.",
  },

  "바둥바둥": {
    name: "바둥바둥",
    type: "노말",
    category: "물리",
    power: null,
    accuracy: 100,
    pp: 15,
    priority: 1,
    rankChange: null,
    effect: null,
    alwaysHit: null,
    description: "바둥바둥 난동부려서 공격한다. 자신의 HP가 적을수록 기술의 위력이 올라간다.",
  },

  "힘껏치기": {
    name: "힘껏치기",
    type: "노말",
    category: "물리",
    power: 50,
    accuracy: 75,
    pp: 20,
    priority: 1,
    rankChange: null,
    effect: null,
    alwaysHit: null,
    description: "긴 꼬리나 덩굴 등을 사용해 상대를 힘껏 쳐서 공격한다.",
  },

  // ── 불꽃 ───────────────────────────────────
  "화염방사": {
    name: "화염방사",
    type: "불꽃",
    category: "특수",
    power: 50,
    accuracy: 100,
    pp: 15,
    priority: 0,
    rankChange: null,
    effect: "10% 확률로 상대를 화상 상태로 만든다.",
    alwaysHit: false,
    description: "세찬 불꽃을 상대에게 발사하여 공격한다. 화상 상태로 만들 때가 있다.",
  },

  "불대문자": {
    name: "불대문자",
    type: "불꽃",
    category: "특수",
    power: 60,
    accuracy: 85,
    pp: 5,
    priority: 0,
    rankChange: null,
    effect: "10% 확률로 상대를 화상 상태로 만든다.",
    alwaysHit: false,
    description: "큰 대자의 불꽃으로 상대를 불태운다. 화상 상태로 만들 때가 있다.",
  },

  "불꽃세례": {
    name: "불꽃세례",
    type: "불꽃",
    category: "특수",
    power: 30,
    accuracy: 100,
    pp: 25,
    priority: 0,
    rankChange: null,
    effect: "10% 확률로 상대를 화상 상태로 만든다.",
    alwaysHit: false,
    description: "작은 불꽃을 상대에게 발사하여 공격한다. 화상 상태로 만들 때가 있다.",
  },

    "화염바퀴": {
    name: "화염바퀴",
    type: "불꽃",
    category: "특수",
    power: 40,
    accuracy: 100,
    pp: 25,
    priority: 0,
    rankChange: null,
    effect: "10% 확률로 상대를 화상 상태로 만든다.",
    alwaysHit: false,
    description: "불꽃을 둘러 상대에게 돌진 공격한다. 10% 확률로 상대를 화상 상태로 만든다.",
  },

  // ── 물 ───────────────────────────────────
  "열탕": {
    name: "열탕",
    type: "물",
    category: "특수",
    power: 50,
    accuracy: 100,
    pp: 15,
    priority: 0,
    rankChange: null,
    effect: "30% 확률로 상대를 화상 상태로 만든다.",
    alwaysHit: false,
    description: "뜨겁게 끓어오르는 물을 상대에게 발사해서 공격한다. 화상 상태로 만들 때가 있다.",
  },

  "파도타기": {
    name: "파도타기",
    type: "물",
    category: "특수",
    power: 50,
    accuracy: 100,
    pp: 15,
    priority: 0,
    rankChange: null,
    effect: null,
    alwaysHit: false,
    description: "큰 파도로 주위에 있는 모든 것을 공격한다.",
  },

  "하이드로펌프": {
    name: "하이드로펌프",
    type: "물",
    category: "특수",
    power: 60,
    accuracy: 80,
    pp: 5,
    priority: 0,
    rankChange: null,
    effect: null,
    alwaysHit: false,
    description: "대량의 물을 세찬 기세로 상대에게 발사하여 공격한다.",
  },

  "물대포": {
    name: "물대포",
    type: "물",
    category: "특수",
    power: 30,
    accuracy: 100,
    pp: 25,
    priority: 0,
    rankChange: null,
    effect: null,
    alwaysHit: false,
    description: "물을 기세 좋게 상대에게 발사하여 공격한다.",
  },

  // ── 전기 ─────────────────────────────────
  "10만볼트": {
    name: "10만볼트",
    type: "전기",
    category: "특수",
    power: 50,
    accuracy: 100,
    pp: 15,
    priority: 0,
    rankChange: null,
    effect: "10% 확률로 상대를 마비 상태로 만든다.",
    alwaysHit: false,
    description: "강한 전격을 상대에게 날려서 공격한다. 마비 상태로 만들 때가 있다.",
  },

  "번개": {
    name: "번개",
    type: "전기",
    category: "특수",
    power: 60,
    accuracy: 70,
    pp: 10,
    priority: 0,
    rankChange: null,
    effect: "30% 확률로 상대를 마비 상태로 만든다.",
    alwaysHit: false,
    description: "강한 번개를 상대에게 떨어뜨려 공격한다. 마비 상태로 만들 때가 있다.",
  },

  "볼부비부비": {
    name: "볼부비부비",
    type: "전기",
    category: "특수",
    power: 30,
    accuracy: 100,
    pp: 20,
    priority: 0,
    rankChange: null,
    effect: "상대를 마비 상태로 만든다.",
    alwaysHit: false,
    description: "전기가 흐르는 볼을 비벼서 공격한다. 상대를 마비 상태로 만든다.",
  },

  // ── 풀 ───────────────────────────────────
  "에너지볼": {
    name: "에너지볼",
    type: "풀",
    category: "특수",
    power: 50,
    accuracy: 100,
    pp: 10,
    priority: 0,
    rankChange: { target: "foe", stat: "def", stage: -1 },
    effect: null,
    effect: "10% 확률로 상대의 방어가 -1 하락한다.",
    alwaysHit: false,
    description: "자연으로부터 생명의 힘을 모아서 발사한다. 상대의 방어를 떨어뜨릴 때가 있다.",
  },

  "흡수": {
    name: "흡수",
    type: "풀",
    category: "특수",
    power: 30,
    accuracy: 100,
    pp: 25,
    priority: 0,
    rankChange: null,
    effect: null,
    effect: "상대에게 준 피해의 12%만큼 체력을 회복한다.",
    alwaysHit: false,
    description: "양분을 흡수하여 공격한다. 상대에게 준 피해의 12%만큼 체력을 회복한다.",
  },

  // ── 얼음 ─────────────────────────────────
  "냉동빔": {
    name: "냉동빔",
    type: "얼음",
    category: "특수",
    power: 50,
    accuracy: 100,
    pp: 10,
    priority: 0,
    rankChange: null,
    effect: "10% 확률로 상대를 얼음 상태로 만든다.",
    alwaysHit: false,
    description: "냉동빔을 상대에게 발사하여 공격한다. 얼음 상태로 만들 때가 있다.",
  },

  // ── 격투 ─────────────────────────────────
  "인파이트": {
    name: "인파이트",
    type: "격투",
    category: "물리",
    power: 60,
    accuracy: 100,
    pp: 5,
    priority: 0,
    rankChange: { target: "self", stat: "def", stage: -1 },
    effect: "사용 후 자신의 방어가 -1 하락한다.",
    alwaysHit: false,
    description: "방어를 포기하고 상대 쪽으로 깊숙이 돌격한다. 자신의 방어가 떨어진다.",
  },

  "깨트리기": {
    name: "깨트리기",
    type: "격투",
    category: "물리",
    power: 45,
    accuracy: 100,
    pp: 15,
    priority: 0,
    rankChange: null,
    effect: null,
    alwaysHit: false,
    description: "수도로 기세 좋게 내려쳐서 상대를 공격한다.",
  },

  "무릎차기": {
    name: "무릎차기",
    type: "격투",
    category: "물리",
    power: 70,
    accuracy: 90,
    pp: 10,
    priority: 0,
    rankChange: null,
    effect: null,
    alwaysHit: false,
    description: "점프해서 무릎차기로 상대를 공격한다. 빗나가면 자신이 전체 HP의 1/4의 피해를 입는다.",
  },

    "파동탄": {
    name: "파동탄",
    type: "격투",
    category: "물리",
    power: 45,
    accuracy: null,
    pp: 20,
    priority: 0,
    rankChange: null,
    effect: null,
    alwaysHit: true,
    description: "몸 속에서 파동의 힘을 끌어내 쏜다. 공격은 반드시 명중한다.",
  },

  // ── 에스퍼 ───────────────────────────────
  "사이코키네시스": {
    name: "사이코키네시스",
    type: "에스퍼",
    category: "특수",
    power: 50,
    accuracy: 100,
    pp: 10,
    priority: 0,
    rankChange: { target: "foe", stat: "def", stage: -1 },
    effect: "10% 확률로 상대의 방어가 -1 하락한다.",
    alwaysHit: false,
    description: "강한 염동력을 상대에게 보내어 공격한다. 상대의 방어를 떨어뜨릴 때가 있다.",
  },

  // ── 악 ───────────────────────────────────
  "악의파동": {
    name: "악의파동",
    type: "악",
    category: "특수",
    power: 50,
    accuracy: 100,
    pp: 15,
    priority: 0,
    rankChange: null,
    effect: "20% 확률로 상대를 풀죽게 만든다.",
    alwaysHit: false,
    description: "몸에서 악의로 가득한 무서운 오라를 발한다. 상대를 풀죽게 만들 때가 있다.",
  },

  // ── 드래곤 ───────────────────────────────
  "용의파동": {
    name: "용의파동",
    type: "드래곤",
    category: "특수",
    power: 40,
    accuracy: 100,
    pp: 10,
    priority: 0,
    rankChange: null,
    effect: null,
    alwaysHit: false,
    description: "큰 입으로 충격파를 일으켜서 상대를 공격한다.",
  },

  "와이드브레이커": {
    name: "와이드브레이커",
    type: "드래곤",
    category: "특수",
    power: 40,
    accuracy: 100,
    pp: 15,
    priority: 0,
    rankChange: { target: "foe", stat: "atk", stage: -1 },
    effect: null,
    alwaysHit: "상대의 공격이 -1 하락한다.",
    description: "강인한 꼬리를 세차게 휘둘러서 상대를 공격한다. 상대의 공격을 -1 떨어뜨린다.",
  },

  "용성군": {
    name: "용성군",
    type: "드래곤",
    category: "특수",
    power: 70,
    accuracy: 90,
    pp: 5,
    priority: 0,
    rankChange: { target: "self", stat: "atk", stage: -2 },
    effect: "사용 후 자신의 공격이 -2 하락한다.",
    alwaysHit: false,
    description: "천공에서 운석을 떨어뜨린다. 사용하면 반동으로 자신의 공격이 -2 떨어진다.",
  },

  // ── 벌레 ───────────────────────────────────
  "달려들기": {
    name: "달려들기",
    type: "벌레",
    category: "특수",
    power: 40,
    accuracy: 100,
    pp: 20,
    priority: 0,
    rankChange: { target: "foe", stat: "spd", stage: -1 },
    effect: null,
    alwaysHit: false,
    description: "상대에게 달려들어 공격한다. 상대의 스피드를 -1 떨어뜨린다.",
  },

  "흡혈": {
    name: "흡혈",
    type: "벌레",
    category: "특수",
    power: 50,
    accuracy: 100,
    pp: 10,
    priority: 0,
    rankChange: null,
    effect: null,
    effect: "상대에게 준 피해의 12%만큼 체력을 회복한다.",
    alwaysHit: false,
    description: "피를 빨아서 상대를 공격한다. 상대에게 준 피해의 12%만큼 체력을 회복한다.",
  },

 // ── 땅 ───────────────────────────────────
 "머드샷": {
    name: "머드샷",
    type: "땅",
    category: "특수",
    power: 40,
    accuracy: 95,
    pp: 15,
    priority: 0,
    rankChange: { target: "foe", stat: "spd", stage: -1 },
    effect: null,
    alwaysHit: false,
    description: "진흙 덩어리를 상대에게 내던져서 공격한다. 상대의 스피드를 -1 떨어뜨린다.",
  },

  "분함의발구르기": {
    name: "분함의발구르기",
    type: "땅",
    category: "특수",
    power: 45,
    accuracy: 100,
    pp: 15,
    priority: 0,
    rankChange: null,
    effect: "직전 턴의 기술이 빗나갔다면 최종 피해 ×1.3",
    alwaysHit: false,
    description: "분함을 발판삼아 공격한다. 앞 턴에서 기술이 빗나갔다면 위력이 1.3배가 된다.",
  },

  // ── 독 ───────────────────────────────────
  "용해액": {
    name: "용해액",
    type: "독",
    category: "특수",
    power: 30,
    accuracy: 100,
    pp: 30,
    priority: 0,
    rankChange: { target: "foe", stat: "def", stage: -1 },
    effect: "10% 확률로 상대의 방어가 -1 하락한다.",
    alwaysHit: false,
    description: "강한 산을 상대에게 끼얹어 공격한다. 10% 확률로 상대의 방어를 -1 떨어뜨린다.",
  },

  // ── 고스트 ───────────────────────────────────
  "고스트다이브": {
    name: "고스트다이브",
    type: "고스트",
    category: "특수",
    power: 50,
    accuracy: 100,
    pp: 10,
    priority: 0,
    rankChange: null,
    effect: null,
    alwaysHit: false,
    description: "1턴째에 어디론가 사라져서 2턴째에 상대를 공격한다. 기술 방어를 무시하고 공격할 수 있다.",
  },

  "섀도볼": {
    name: "섀도볼",
    type: "고스트",
    category: "특수",
    power: 50,
    accuracy: 100,
    pp: 15,
    priority: 0,
    rankChange: { target: "foe", stat: "def", stage: -1 },
    effect: "20% 확률로 상대의 방어가 -1 하락한다.",
    alwaysHit: false,
    description: "까만 그림자의 덩어리를 내던져서 공격한다. 20% 확률로 상대의 방어를 -1 떨어뜨린다.",
  },

};
